raw_data_dir: data/raw
processed_data_dir: data/processed
interim_data_dir: data/interim
results_dir: results
data_dir: data
scripts_dir: scripts
embedding_parquet_dir: data/raw/datasets/major-tom-core-s2l1c-ssl4eo-amazonia-embeddings

# Coordinate reference systems
aoi_crs: EPSG:4326
metric_crs: EPSG:3857
aoi_box : [-80.85832999999998, -28.60999999999999, -35.5853, 11.799999999999999]
