version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
      - ./results:/app/results
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=secret-token