version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
      - ./results:/app/results
      - ./secrets:/app/secrets:ro
    ports:
      - "8888:8888"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/ee-sa-key.json
